version: "3.8"
services:

  backend:
    build: docker/dev/backend
    ports:
      - "3000:3000"
    expose: 
      - "3000"
    networks:
      - wichtelomat
    volumes: 
      - ./backend:/app
      - ./db-data:/db-data

  frontend:
    build: docker/dev/frontend
    ports:
      - "3001:3000"
    expose: 
      - "3000"
    networks:
      - wichtelomat
    volumes: 
      - ./frontend:/src

networks:
  wichtelomat:
